version: '3.8'

services:
  groundingdino:
    build: ./grounding_dino
    container_name: groundingdino
    ports:
      - "8001:8001"

  gemini2:
    build: ./gemini2
    container_name: gemini2
    ports:
      - "8002:8002"
    
  streamlit:
    build: ./st_appq
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - groundingdino
      - gemini2

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" 
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
